### ISSUE TITLE
[ BUG ] IoaRuleGroup.__repr__() raises AttributeError

### ISSUE THREAD

**Issue by scottzach1** [CrowdStrike/caracara#213]
# Bug Report Template

## Describe the bug

Custom IOA Rule models raise an `AttributeError` when `repr()` is called on them when instantiated using `__init__()`.

## To Reproduce

```python
from caracara.modules.custom_ioa import IoaRuleGroup

irg = IoaRuleGroup("name", "description", "platform")

repr(irg)
```

```
Traceback (most recent call last):
  File "/home/zaci/PycharmProjects/Caracara-Reproduce/.venv/lib/python3.10/site-packages/caracara/modules/custom_ioa/rules.py", line 66, in __repr__
    f"<{self.__class__.__name__}(id_={repr(self.id_)}, version={repr(self.version)}, "
AttributeError: 'IoaRuleGroup' object has no attribute 'version'
```

## Expected behavior

There should be no state of IoaRuleGroup where a `repr()` cannot be displayed.

### Operating System Version

Linux arch 6.11.2-arch1-1 #\1 SMP PREEMPT_DYNAMIC Fri, 04 Oct 2024 21:51:11 +0000 x86_64 GNU/Linux

### Python Version

- Python 3.10.14
- Python 3.12.6

### Poetry Version

Poetry (version 1.8.3)

### Python Package Versions

```
caracara==0.8.0
caracara-filters==0.2.0
crowdstrike-falconpy==1.4.5
```

## Additional context

If you are wanting to distinguish between unset and null variables then one approach could be to use a [sentinel object](https://python-patterns.guide/python/sentinel-object/).

```python
# sentinel.py
class Unset:
    def __str__(self):
        return ""

    def __repr__(self):
        return "<empty>"

    def __bool__(self):
        return False
```

```python
# my_model.py
UNSET = Unset()  # sentinel object


class MyModel:
    a: str = UNSET
    b: str = UNSET

    def __init__(self, a: str):
        self.a = a

    def __repr__(self):
        return f"<MyModel(a={self.a!r}, b={self.b!r})>"


m = MyModel("example")
assert repr(m) == "<MyModel(a='example', b=<empty>)>"
```

*edit: Added Sentinel class for tidier `__repr__`

**Comment by scottzach1** [comment]
After some further playing around I noticed that in a similar note accessing the cloud fields on the models also raises an attribute error. This is documented in the inline comments but I think this would also be improved with sentinel values.

```python
from caracara.modules.custom_ioa import CustomIoaRule

rule = CustomIoaRule("name", "description", <rule_type>)
rule.deleted  # raises AttributeError
```

**Comment by ChristopherHammond13** [comment]
Thank you also for raising this issue, Zac! Assigning myself to this one, too. Going to think about how to architect this one a little better.
