### ISSUE TITLE
[ BUG ] Failing unit tests for `CustomIoaApiModule`

### ISSUE THREAD

**Issue by hur** [CrowdStrike/caracara#219]
## Describe the bug

The unit test `test_describe_rule_groups_with_rules` is failing.

## To Reproduce

`pytest tests/unit_tests/test_custom_ioas.py`

## Expected behavior

Tests pass

### Operating System Version

MacOS 14.7

### Python Version

Python 3.11.9

### Poetry Version

Poetry (version 1.8.4)

## Additional context

The unit tests fail because the mocked data is modified by the `_update_create_delete` function, and the key `rulegroup_id` is added to the raw data, but not used in the `CustomIoaRule` object:

```python3
raw_rule["rulegroup_id"] = rule_group.id_  # API doesn't populate this field, so we do
```

Additionally, CustomIoaRule.dump() does not return the rulegroup id.

**Comment by ChristopherHammond13** [comment]
Resolved!
